### PR TITLE
fix: prevent repeated sandbox expiry cleanup attempts

### LINKED ISSUE #228: Sandbox expiry handler runs repeatedly after expiration
The `handleSandboxExpiry` function runs on every reconciliation loop after a sandbox's shutdownTime has passed, even after the sandbox has already been marked as expired. This causes the controller to repeatedly attempt deletion of already-deleted Pods and Services.

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #228

The lifecycle design is "once expired, always expired".

### CODE REVIEW

File: controllers/sandbox_controller.go [hunk 1]
```diff
@@ -90,6 +90,13 @@ func (r *SandboxReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		return ctrl.Result{}, err
 	}
 
+	// Check if already marked as expired to avoid repeated operations, including cleanups
+	if sandboxMarkedExpired(sandbox) {
```
Comment (barney-s) [inline controllers/sandbox_controller.go:100]: This check is currently placed before the `DeletionTimestamp` check (lines 106-109). If the Sandbox resource has any finalizers (either now or added in the future), this early return will prevent the finalizers from being processed and removed, causing the resource deletion to hang indefinitely. Please move this check *after* the deletion timestamp check.

File: controllers/sandbox_controller.go [hunk 2]
```diff
@@ -90,6 +90,13 @@ func (r *SandboxReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
+		log.Info("Sandbox is already marked as expired")
+		// Note: the sandbox won't be deleted if shutdown policy is changed to delete after expiration.
+		return ctrl.Result{}, nil
```
Comment (barney-s) [inline controllers/sandbox_controller.go:105]: This early return prevents the sandbox from being deleted if the `ShutdownPolicy` is changed to `Delete` *after* expiration. While this aligns with the "once expired, always expired" philosophy, it effectively freezes the resource configuration. Please ensure this limitation is acceptable and consider if a check for policy changes is needed here.

File: controllers/sandbox_controller.go [hunk 3]
```diff
@@ -537,6 +547,17 @@ func checkSandboxExpiry(sandbox *sandboxv1alpha1.Sandbox) (bool, time.Duration)
 	return false, requeueAfter
 }
 
+// sandboxMarkedExpired checks if the sandbox is already marked as expired
```
Comment (barney-s) [inline controllers/sandbox_controller.go:553]: Instead of manually iterating over conditions, consider using `meta.FindStatusCondition(sandbox.Status.Conditions, string(sandboxv1alpha1.SandboxConditionReady))` from `k8s.io/apimachinery/pkg/api/meta`. It simplifies the code and is the standard way to look up conditions.

File: controllers/sandbox_controller.go (hunk 2 above)
Comment (janetkuo) [reply controllers/sandbox_controller.go:105]: As documented in this comment here, this is intentional. 

If the user wants the claim to be deleted after it's already expired, they could just do a Delete. If we support this operation, they would need to do an Update, which is not simpler than sending a Delete, and makes the controller code more complicated. 

Added more comments to explain the logic.

File: controllers/sandbox_controller.go (hunk 1 above)
Comment (janetkuo) [reply controllers/sandbox_controller.go:100]: The DeletionTimestamp check only prints the log for now (no finalizers). However, moving it up allows us to return early. Done.

File: controllers/sandbox_controller.go (hunk 3 above)
Comment (janetkuo) [reply controllers/sandbox_controller.go:553]: Done
